image: qwe1/dind-ansible-molecule

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test

test:
  stage: test
  image: qwe1/dind-ansible-molecule
  script:
    - id
    - ansible-playbook -i hosts pb.yml