image: qwe1/debdocker:20.10
services:
  - name: docker:20.10-dind
    command: ["--experimental"]
variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
before_script:
  - mkdir -p $HOME/.docker/cli-plugins/
  # https://www.thegeekstuff.com/2011/10/grep-or-and-not-operators/
  - export BUILDX_URL="$(wget -O - https://api.github.com/repos/docker/buildx/releases/latest | grep 'browser_download_url.*https://github.com/docker/buildx/releases/download.*linux-amd64' | awk -F'"' '{print $4}')"
  - if [ -z "${BUILDX_URL}" ];then exit 1;fi
  - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  - docker buildx create --use --driver docker-container --name pg --platform=linux/amd64,linux/386,linux/arm/v7,linux/arm64
  - docker buildx inspect --bootstrap pg
  - docker buildx ls
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
  - build

build:
  stage: build
  script:
    # - docker buildx build --push -t qwe1/playground:latest -t qwe1/playground:$CI_COMMIT_SHORT_SHA -f Dockerfile --platform linux/amd64,linux/386,linux/arm/v7,linux/arm64 .
    - docker buildx build --push -t qwe1/playground:latest -t qwe1/playground:$CI_COMMIT_SHORT_SHA -f Dockerfile --platform linux/amd64, linux/arm/v7,linux/arm64 .
    - docker images
    - docker run --rm qwe1/playground:latest bash --version
