image: docker:stable

variables:

  DOCKER_HOST: tcp://docker:2375/

  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  #- env
  - docker info
  - echo "$CI_REGISTRY_USER" "$CI_REGISTRY" "$$CI_REGISTRY_IMAGE"
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin



stages:
  - build

build_image:
  stage: build
  script:
    - echo $CI_REGISTRY "$CI_PROJECT_NAMESPACE" $CI_PROJECT_NAME $CI_COMMIT_SHA
    #- docker build -t registry.gitlab.com/richardskumat/playground:$CI_COMMIT_SHA -t registry.gitlab.com/richardskumat/playground:latest .
    #- docker push registry.gitlab.com/richardskumat/playground:latest
    #- docker push registry.gitlab.com/richardskumat/playground:$CI_COMMIT_SHA
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA
