image: docker:stable

variables:

  DOCKER_HOST: tcp://docker:2375/

  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  #- env
  - docker info
  - echo "$GITLAB_USER_LOGIN" "$CI_REGISTRY"
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$GITLAB_USER_LOGIN" "$CI_REGISTRY" --password-stdin



stages:
  - build

build_image:
  stage: build
  script:
    - echo $CI_REGISTRY "$GITLAB_USER_LOGIN" $CI_PROJECT_NAME $CI_COMMIT_SHA
    #- docker build -t registry.gitlab.com/richardskumat/playground:$CI_COMMIT_SHA -t registry.gitlab.com/richardskumat/playground:latest .
    #- docker push registry.gitlab.com/richardskumat/playground:latest
    #- docker push registry.gitlab.com/richardskumat/playground:$CI_COMMIT_SHA
    - docker build -t $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:latest -t $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:latest
    - docker push $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME:$CI_COMMIT_SHA
