image: docker:stable

variables:

  DOCKER_HOST: tcp://docker:2375/

  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker info
  - echo $CI_REGISTRY_USER $CI_REGISTRY
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY



stages:
  - build
  - test

build_image:
  stage: build
  script:
    - echo $CI_REGISTRY $CI_REGISTRY_USER $CI_PROJECT_NAME $CI_COMMIT_SHA
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest -t $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA

test_image:
  stage: test
  script:
    - docker run $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest
    - docker run $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHA
