#image: qwe1/debdocker:20.10
image: crazymax/docker:latest
services:
  - name: docker:20.10-dind
    command: ["--experimental"]

variables:
  # for some reason docker on gitlab throws context erros with these enabled
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  #DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  RASPBIAN_VERSION: 'bullseye'
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64

before_script:
  - mkdir -p $HOME/.docker/cli-plugins/
  # https://www.thegeekstuff.com/2011/10/grep-or-and-not-operators/
  - export BUILDX_URL="$(wget -O - https://api.github.com/repos/docker/buildx/releases/latest | grep 'browser_download_url.*https://github.com/docker/buildx/releases/download.*linux-amd64' | awk -F'"' '{print $4}')"
  - if [ -z "${BUILDX_URL}" ];then exit 1;fi
  - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # https://gitlab.com/richardskumat/playground/-/jobs/2762899800
  - docker context create whatever
  - docker buildx create whatever
  ##
  - docker buildx create --use --driver docker-container --name whatever --platform=linux/amd64,linux/arm/v7,linux/arm64
  - docker buildx inspect --bootstrap whatever
  - docker buildx ls
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

stages:
  - build

build_raspbian:
  stage: build
  image: qwe1/debdocker:latest
  script:
    # https://raspberrypi.stackexchange.com/questions/78232/install-base-raspbian-from-repository-not-using-an-image
    - apt-get update && apt-get install wget binfmt-support qemu qemu-user-static debootstrap -y
    - wget http://archive.raspbian.org/raspbian.public.key -O - | apt-key add -q
    - df -hT
    - mount
    #- qemu-debootstrap --keyring=/etc/apt/trusted.gpg --arch armhf --variant=minbase $RASPBIAN_VERSION $RASPBIAN_VERSION http://mirrordirector.raspbian.org/raspbian/
    - debootstrap --include apt --keyring=/etc/apt/trusted.gpg --foreign --arch armhf --variant=minbase $RASPBIAN_VERSION /tmp/$RASPBIAN_VERSION http://mirrordirector.raspbian.org/raspbian/
    # https://docs.docker.com/develop/develop-images/baseimages/
    - tar -C /tmp/$RASPBIAN_VERSION -c . | docker import - $RASPBIAN_VERSION
    - docker run --rm $RASPBIAN_VERSION cat /etc/os-release
    - docker run --rm $RASPBIAN_VERSION cat /etc/apt/sources.list
    - docker run --rm $RASPBIAN_VERSION apt-get update
    - docker images
    - ls -lah
