image: docker:stable

variables:
  # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  #- env
  - echo "$CI_REGISTRY_USER" "$CI_REGISTRY" "$CI_REGISTRY_IMAGE"
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin



stages:
  - build

build_image:
  stage: build
  script:
    - echo $CI_REGISTRY "$CI_PROJECT_NAMESPACE" $CI_PROJECT_NAME $CI_COMMIT_SHA
    - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
